import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";
import { logoutSession, readSession, requireAdmin, requireUser, setSession } from "@/lib/auth";
import { supabaseRest } from "@/lib/db";
import { hashPassword, verifyPassword } from "@/lib/security";
import { PROFILES } from "@/lib/vibe-data";

const registrationSchema=z.object({name:z.string().trim().min(3).max(80),username:z.string().trim().toLowerCase().regex(/^[a-z0-9_]{3,30}$/),email:z.string().trim().email().max(120),phone:z.string().trim().regex(/^(0|255)\d{9}$/),country:z.string().trim().min(2).max(50),password:z.string().min(6).max(100)});
function normalizePhone(raw:string){const d=raw.replace(/\D/g,"");if(d.startsWith("255"))return d;if(d.startsWith("0"))return `255${d.slice(1)}`;return d.length===9?`255${d}`:d;}
function tableUser(id:string){return supabaseRest<Array<Record<string,unknown>>>("naravibe_users",{query:{select:"id,name,username,email,phone,country,status,role,balance,withdrawn,created_at,activated_at",id:`eq.${id}`,limit:1}});}

export const registerUser=createServerFn({method:"POST"}).validator(registrationSchema).handler(async({data})=>{const username=data.username.toLowerCase();const email=data.email.toLowerCase();const phone=normalizePhone(data.phone);const existing=await supabaseRest<Array<Record<string,unknown>>>("naravibe_users",{query:{select:"id,username,email,phone",or:`(username.eq.${username},email.eq.${email},phone.eq.${phone})`,limit:1}});if(existing.length){const r=existing[0]??{};if(String(r.username??"").toLowerCase()===username)throw new Error("USERNAME_EXISTS");throw new Error("EMAIL_OR_PHONE_EXISTS");}const {hash,salt}=await hashPassword(data.password);const created=await supabaseRest<Array<Record<string,unknown>>>("naravibe_users",{method:"POST",body:{name:data.name,username,email,phone,country:data.country,password_hash:hash,password_salt:salt,status:"pending",role:"user",balance:0,withdrawn:0}});const user=created[0];if(!user?.id)throw new Error("REGISTRATION_FAILED");await setSession({userId:String(user.id),role:"user"});return{id:String(user.id),status:"pending",activationFee:Number(process.env.ACTIVATION_FEE||process.env.VITE_ACTIVATION_FEE||"15000")};});

export const loginUser=createServerFn({method:"POST"}).validator(z.object({username:z.string().trim().toLowerCase().min(3).max(30),password:z.string().min(1)})).handler(async({data})=>{const rows=await supabaseRest<Array<Record<string,unknown>>>("naravibe_users",{query:{select:"id,password_hash,password_salt,status,role",username:`eq.${data.username.toLowerCase()}`,limit:1}});const u=rows[0];if(!u||u.role!=="user"||!(await verifyPassword(data.password,String(u.password_hash),String(u.password_salt))))throw new Error("INVALID_LOGIN");if(["banned","inactive"].includes(String(u.status)))throw new Error(String(u.status).toUpperCase());await setSession({userId:String(u.id),role:"user"});return{status:String(u.status)};});

export const getMe=createServerFn({method:"GET"}).handler(async()=>{const s=await readSession();if(!s.userId||s.role!=="user")return{user:null};const rows=await tableUser(s.userId);return{user:rows[0]??null};});

export const submitManualPayment=createServerFn({method:"POST"}).validator(z.object({phone:z.string().regex(/^\d{9,15}$/)})).handler(async({data})=>{const userId=await requireUser();const phone=normalizePhone(data.phone);const amount=Number(process.env.ACTIVATION_FEE||process.env.VITE_ACTIVATION_FEE||"15000");await supabaseRest("naravibe_activation_payments",{method:"POST",body:{user_id:userId,method:"lipa_namba",amount,phone,external_id:process.env.LIPA_NUMBER||"251161660",status:"pending",metadata:{business:process.env.LIPA_BUSINESS||"NARAVIBE",lipa_number:process.env.LIPA_NUMBER||"251161660"}}});await supabaseRest("naravibe_notifications",{method:"POST",body:{user_id:userId,title:"Malipo yametumwa kwa ukaguzi",message:"Tumepokea taarifa yako ya Lipa Namba. Admin atakagua muamala kabla ya ku-activate akaunti.",type:"info"}});return{ok:true};});

export const getNotifications=createServerFn({method:"GET"}).handler(async()=>{const userId=await requireUser();const rows=await supabaseRest<Array<Record<string,unknown>>>("naravibe_notifications",{query:{select:"id,title,message,type,created_at",or:`(user_id.is.null,user_id.eq.${userId})`,order:"created_at.desc",limit:20}});return{notifications:rows};});
export const logout=createServerFn({method:"POST"}).handler(async()=>{await logoutSession();return{ok:true};});

export const requestWithdrawal=createServerFn({method:"POST"}).validator(z.object({amount:z.number().int().min(50000),method:z.string().min(2),accountNumber:z.string().min(5).max(30)})).handler(async({data})=>{const userId=await requireUser();const rows=await tableUser(userId);const u=rows[0];const balance=Number(u?.balance??0);if(u?.status!=="active")throw new Error("ACCOUNT_NOT_ACTIVE");if(data.amount>balance)throw new Error("INSUFFICIENT_BALANCE");await supabaseRest("naravibe_withdrawals",{method:"POST",body:{user_id:userId,amount:data.amount,method:data.method,account_number:data.accountNumber,status:"pending"}});await supabaseRest("naravibe_notifications",{method:"POST",body:{user_id:userId,title:"Withdrawal imeombwa",message:`Ombi la withdrawal la TZS ${data.amount.toLocaleString()} limetumwa kwa admin kwa ukaguzi.`,type:"info"}});return{ok:true};});

export const completeChat=createServerFn({method:"POST"}).validator(z.object({sessionId:z.string().uuid(),personName:z.string().trim().min(1).max(100)})).handler(async({data})=>{const userId=await requireUser();const users=await tableUser(userId);const user=users[0];if(!user||String(user.status)!=="active")throw new Error("ACCOUNT_NOT_ACTIVE");const person=PROFILES.find(p=>p.name.toLowerCase()===data.personName.trim().toLowerCase());if(!person)throw new Error("FOREIGNER_NOT_FOUND");const payout=Number(person.tzs||0);const existing=await supabaseRest<Array<Record<string,unknown>>>("naravibe_chat_sessions",{query:{select:"id,status,payout,message_count,completed_at",session_id:`eq.${data.sessionId}`,user_id:`eq.${userId}`,limit:1}});const row=existing[0];if(row&&String(row.status)==="completed")return{ok:true,balance:Number(user.balance??0),payout:Number(row.payout??payout),alreadyCompleted:true};if(row){await supabaseRest("naravibe_chat_sessions",{method:"PATCH",query:{id:`eq.${row.id}`},body:{message_count:20,status:"completed",completed_at:new Date().toISOString(),payout}});const updated=await supabaseRest<Array<Record<string,unknown>>>("naravibe_users",{method:"PATCH",query:{id:`eq.${userId}`},body:{balance:Number(user.balance??0)+payout},prefer:"return=representation"});return{ok:true,balance:Number(updated[0]?.balance??Number(user.balance??0)+payout),payout,alreadyCompleted:false};}try{await supabaseRest("naravibe_chat_sessions",{method:"POST",body:{session_id:data.sessionId,user_id:userId,person_name:data.personName.trim(),payout,message_count:20,status:"completed",completed_at:new Date().toISOString()}});}catch(err){const check=await supabaseRest<Array<Record<string,unknown>>>("naravibe_chat_sessions",{query:{select:"id,status,payout",session_id:`eq.${data.sessionId}`,user_id:`eq.${userId}`,limit:1}});const duplicate=check[0];if(duplicate&&String(duplicate.status)==="completed")return{ok:true,balance:Number(user.balance??0),payout:Number(duplicate.payout??payout),alreadyCompleted:true};throw err;}const updated=await supabaseRest<Array<Record<string,unknown>>>("naravibe_users",{method:"PATCH",query:{id:`eq.${userId}`},body:{balance:Number(user.balance??0)+payout},prefer:"return=representation"});return{ok:true,balance:Number(updated[0]?.balance??Number(user.balance??0)+payout),payout,alreadyCompleted:false};});
export const adminLogin=createServerFn({method:"POST"}).validator(z.object({email:z.string().trim().email(),password:z.string().min(1)})).handler(async({data})=>{const rows=await supabaseRest<Array<Record<string,unknown>>>("naravibe_users",{query:{select:"id,email,password_hash,password_salt,status,role",email:`eq.${data.email.trim().toLowerCase()}`,limit:1}});const a=rows[0];if(!a)throw new Error("ADMIN_NOT_FOUND");if(a.role!=="admin")throw new Error("NOT_ADMIN");if(a.status!=="active")throw new Error("ADMIN_NOT_ACTIVE");if(!(await verifyPassword(data.password,String(a.password_hash),String(a.password_salt))))throw new Error("INVALID_ADMIN_PASSWORD");await setSession({userId:String(a.id),role:"admin"});return{ok:true};});

export const adminLogout=createServerFn({method:"POST"}).handler(async()=>{await logoutSession();return{ok:true};});
export const getAdminData=createServerFn({method:"GET"}).handler(async()=>{await requireAdmin();const [users,payments,withdrawals,notifications]=await Promise.all([supabaseRest<Array<Record<string,unknown>>>("naravibe_users",{query:{select:"id,name,username,email,phone,country,status,role,balance,withdrawn,created_at,activated_at",order:"created_at.desc",limit:300}}),supabaseRest<Array<Record<string,unknown>>>("naravibe_activation_payments",{query:{select:"id,user_id,method,amount,phone,status,created_at,confirmed_at,reviewed_at,external_id",order:"created_at.desc",limit:300}}),supabaseRest<Array<Record<string,unknown>>>("naravibe_withdrawals",{query:{select:"id,user_id,amount,method,account_number,status,created_at,reviewed_at",order:"created_at.desc",limit:300}}),supabaseRest<Array<Record<string,unknown>>>("naravibe_notifications",{query:{select:"id,user_id,title,message,type,created_at",order:"created_at.desc",limit:100}})]);return{users,payments,withdrawals,notifications};});

export const adminSetUserStatus=createServerFn({method:"POST"}).validator(z.object({userId:z.string().uuid(),status:z.enum(["active","inactive","banned","pending","rejected"])})).handler(async({data})=>{await requireAdmin();const now=new Date().toISOString();await supabaseRest("naravibe_users",{method:"PATCH",query:{id:`eq.${data.userId}`},body:{status:data.status,...(data.status==="active"?{activated_at:now}:{})}});const messages:Record<string,string>={active:"Akaunti yako imewashwa. Unaweza kuendelea kutumia huduma.",inactive:"Akaunti yako imezuiwa kwa muda. Wasiliana na support.",banned:"Akaunti yako imefungwa.",pending:"Akaunti yako imerudishwa pending.",rejected:"Akaunti yako imekataliwa."};await supabaseRest("naravibe_notifications",{method:"POST",body:{user_id:data.userId,title:`Akaunti ${data.status}`,message:messages[data.status],type:data.status==="active"?"success":data.status==="banned"?"error":"warning"}});return{ok:true};});

export const adminReviewPayment=createServerFn({method:"POST"}).validator(z.object({paymentId:z.string().uuid(),action:z.enum(["approve","reject"])})).handler(async({data})=>{await requireAdmin();const rows=await supabaseRest<Array<Record<string,unknown>>>("naravibe_activation_payments",{query:{select:"id,user_id,status,amount",id:`eq.${data.paymentId}`,limit:1}});const payment=rows[0];if(!payment)throw new Error("PAYMENT_NOT_FOUND");const status=data.action==="approve"?"approved":"rejected";await supabaseRest("naravibe_activation_payments",{method:"PATCH",query:{id:`eq.${data.paymentId}`},body:{status,reviewed_at:new Date().toISOString()}});const userId=String(payment.user_id);if(data.action==="approve"){await supabaseRest("naravibe_users",{method:"PATCH",query:{id:`eq.${userId}`},body:{status:"active",activated_at:new Date().toISOString()}});await supabaseRest("naravibe_notifications",{method:"POST",body:{user_id:userId,title:"Akaunti ime-activate 🎉",message:"Malipo yako yamehakikiwa. Ingia Dashboard kuanza.",type:"success"}});}else await supabaseRest("naravibe_notifications",{method:"POST",body:{user_id:userId,title:"Malipo yamekataliwa",message:"Admin hakuthibitisha taarifa ya malipo yako.",type:"error"}});return{ok:true};});

export const adminReviewWithdrawal=createServerFn({method:"POST"}).validator(z.object({withdrawalId:z.string().uuid(),action:z.enum(["approve","reject"])})).handler(async({data})=>{await requireAdmin();const rows=await supabaseRest<Array<Record<string,unknown>>>("naravibe_withdrawals",{query:{select:"id,user_id,amount,status",id:`eq.${data.withdrawalId}`,limit:1}});const item=rows[0];if(!item)throw new Error("WITHDRAWAL_NOT_FOUND");if(item.status!=="pending")return{ok:true};const userId=String(item.user_id);const amount=Number(item.amount);if(data.action==="approve"){const u=await tableUser(userId);const balance=Number(u[0]?.balance??0);if(balance<amount)throw new Error("INSUFFICIENT_BALANCE");await supabaseRest("naravibe_users",{method:"PATCH",query:{id:`eq.${userId}`},body:{balance:balance-amount,withdrawn:Number(u[0]?.withdrawn??0)+amount}});}await supabaseRest("naravibe_withdrawals",{method:"PATCH",query:{id:`eq.${data.withdrawalId}`},body:{status:data.action==="approve"?"approved":"rejected",reviewed_at:new Date().toISOString()}});await supabaseRest("naravibe_notifications",{method:"POST",body:{user_id:userId,title:data.action==="approve"?"Withdrawal imeidhinishwa":"Withdrawal imekataliwa",message:data.action==="approve"?`Withdrawal ya TZS ${amount.toLocaleString()} imeidhinishwa.`:"Ombi lako la withdrawal limekataliwa.",type:data.action==="approve"?"success":"error"}});return{ok:true};});

export const adminSendNotification=createServerFn({method:"POST"}).validator(z.object({userId:z.string().uuid().nullable(),title:z.string().trim().min(2).max(120),message:z.string().trim().min(2).max(1000),type:z.enum(["info","success","warning","error"])})).handler(async({data})=>{await requireAdmin();await supabaseRest("naravibe_notifications",{method:"POST",body:{user_id:data.userId,title:data.title,message:data.message,type:data.type}});return{ok:true};});
