import {createFileRoute,useNavigate} from "@tanstack/react-router";
import {useEffect,useState} from "react";
import {useServerFn} from "@tanstack/react-start";
import {adminLogin,getAdminData,adminReviewPayment,adminSetUserStatus,adminReviewWithdrawal,adminSendNotification,logout} from "@/lib/app.functions";
export const Route=createFileRoute("/admin")({component:Admin});
const money=(v:any)=>Number(v??0).toLocaleString("en-US");
function Admin(){
 const nav=useNavigate(); const login=useServerFn(adminLogin),load=useServerFn(getAdminData),reviewP=useServerFn(adminReviewPayment),setStatus=useServerFn(adminSetUserStatus),reviewW=useServerFn(adminReviewWithdrawal),send=useServerFn(adminSendNotification),signout=useServerFn(logout);
 const [logged,setLogged]=useState(false),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[data,setData]=useState<any>({users:[],payments:[],withdrawals:[],notifications:[]}),[error,setError]=useState(""),[busy,setBusy]=useState(""),[msgUser,setMsgUser]=useState(""),[msg,setMsg]=useState("");
 const refresh=async()=>{try{setData(await load());setLogged(true)}catch{setLogged(false)}}; useEffect(()=>{void refresh()},[]);
 const doLogin=async(e:React.FormEvent)=>{e.preventDefault();try{await login({data:{email,password}});setError("");setLogged(true);await refresh()}catch{setError("Admin login imekataa.")}};
 if(!logged)return <main className="min-h-screen grid place-items-center bg-background p-4"><form onSubmit={doLogin} className="w-full max-w-md rounded-3xl bg-card p-6 shadow-card"><h1 className="text-2xl font-black">NARAVIBE Admin</h1><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="Admin email" type="email" className="mt-5 w-full rounded-xl border bg-background p-3"/><input value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password" type="password" className="mt-3 w-full rounded-xl border bg-background p-3"/>{error&&<p className="mt-3 text-sm text-destructive">{error}</p>}<button className="mt-4 w-full rounded-xl bg-primary py-3 font-bold text-primary-foreground">INGIA ADMIN</button></form></main>;
 const action=async(id:string,kind:"approve"|"reject")=>{setBusy(id);try{await reviewP({data:{paymentId:id,action:kind}});await refresh()}finally{setBusy("")}};
 const status=async(id:string,s:"active"|"deactivated"|"banned"|"pending")=>{setBusy(id);try{await setStatus({data:{userId:id,status:s}});await refresh()}finally{setBusy("")}};
 const withdrawal=async(id:string,a:"approve"|"reject")=>{setBusy(id);try{await reviewW({data:{withdrawalId:id,action:a}});await refresh()}finally{setBusy("")}};
 const sendNotice=async(e:React.FormEvent)=>{e.preventDefault();if(!msgUser||!msg)return;await send({data:{userId:msgUser==="all"?null:msgUser,title:"Admin notification",message:msg,type:"info"}});setMsg("");await refresh()};
 return <main className="min-h-screen bg-background pb-16"><div className="mx-auto max-w-6xl p-4"><header className="flex items-center justify-between rounded-3xl bg-card p-5 shadow-card"><div><p className="text-xs font-bold tracking-widest">NARAVIBE</p><h1 className="text-2xl font-black">Admin Panel</h1></div><button onClick={async()=>{await signout();await nav({to:"/"})}} className="rounded-xl bg-secondary px-4 py-2 font-bold">Logout</button></header>
 <section className="mt-5 grid gap-4 md:grid-cols-4">{[["Users",data.users.length],["Pending Payments",data.payments.filter((p:any)=>p.status==="pending").length],["Withdrawals",data.withdrawals.filter((w:any)=>w.status==="pending").length],["Active",data.users.filter((u:any)=>u.status==="active").length]].map(x=><div className="rounded-2xl bg-card p-4 shadow-card" key={String(x[0])}><p className="text-sm text-muted-foreground">{x[0]}</p><p className="mt-1 text-2xl font-black">{x[1]}</p></div>)}</section>
 <section className="mt-5 rounded-3xl bg-card p-4 shadow-card"><h2 className="text-lg font-black">Lipa Namba — taarifa za malipo</h2><div className="mt-3 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b"><th className="p-2">User</th><th className="p-2">Phone</th><th className="p-2">Amount</th><th className="p-2">Time</th><th className="p-2">Action</th></tr></thead><tbody>{data.payments.map((p:any)=><tr key={p.id} className="border-b"><td className="p-2">{String(data.users.find((u:any)=>u.id===p.user_id)?.name??p.user_id)}</td><td className="p-2">{p.phone}</td><td className="p-2 font-bold">TZS {money(p.amount)}</td><td className="p-2">{new Date(p.created_at).toLocaleString()}</td><td className="p-2">{p.status==="pending"?<div className="flex gap-2"><button disabled={busy===p.id} onClick={()=>void action(p.id,"approve")} className="rounded-lg bg-success px-3 py-2 text-xs font-bold text-success-foreground">Activate</button><button disabled={busy===p.id} onClick={()=>void action(p.id,"reject")} className="rounded-lg border px-3 py-2 text-xs font-bold">Reject</button></div>:p.status}</td></tr>)}</tbody></table></div></section>
 <section className="mt-5 rounded-3xl bg-card p-4 shadow-card"><h2 className="text-lg font-black">Users — Activate / Deactivate / Ban / Unban</h2><div className="mt-3 space-y-2">{data.users.map((u:any)=><div key={u.id} className="flex flex-col gap-3 rounded-2xl border p-3 md:flex-row md:items-center"><div className="flex-1"><b>{u.name}</b><p className="text-xs text-muted-foreground">@{u.username} · {u.phone} · {u.email}</p><p className="text-sm">TZS {money(u.balance)} · <b>{u.status}</b></p></div><div className="flex flex-wrap gap-2"><button onClick={()=>void status(u.id,"active")} className="rounded-lg bg-success px-3 py-2 text-xs font-bold text-success-foreground">Activate</button><button onClick={()=>void status(u.id,"deactivated")} className="rounded-lg border px-3 py-2 text-xs font-bold">Deactivate</button><button onClick={()=>void status(u.id,"banned")} className="rounded-lg border border-red-300 px-3 py-2 text-xs font-bold text-red-600">Ban</button><button onClick={()=>void status(u.id,"active")} className="rounded-lg border px-3 py-2 text-xs font-bold">Unban</button></div></div>)}</div></section>
 <section className="mt-5 rounded-3xl bg-card p-4 shadow-card"><h2 className="text-lg font-black">Withdrawals</h2>{data.withdrawals.map((w:any)=><div key={w.id} className="flex flex-col gap-2 border-b py-3 md:flex-row md:justify-between"><span>{w.phone} · TZS {money(w.amount)} · {w.status}</span>{w.status==="pending"&&<div className="flex gap-2"><button onClick={()=>void withdrawal(w.id,"approve")} className="rounded-lg bg-success px-3 py-2 text-xs font-bold text-success-foreground">Approve</button><button onClick={()=>void withdrawal(w.id,"reject")} className="rounded-lg border px-3 py-2 text-xs font-bold">Reject</button></div>}</div>)}</section>
 <section className="mt-5 rounded-3xl bg-card p-4 shadow-card"><h2 className="text-lg font-black">Send Notification</h2><form onSubmit={sendNotice} className="mt-3"><select value={msgUser} onChange={e=>setMsgUser(e.target.value)} className="w-full rounded-xl border bg-background p-3"><option value="">Select user</option><option value="all">All users</option>{data.users.map((u:any)=><option value={u.id} key={u.id}>{u.name} (@{u.username})</option>)}</select><textarea value={msg} onChange={e=>setMsg(e.target.value)} placeholder="Ujumbe" className="mt-3 min-h-24 w-full rounded-xl border bg-background p-3"/><button className="mt-3 rounded-xl bg-primary px-5 py-3 font-bold text-primary-foreground">TUMA NOTIFICATION</button></form></section>
 </div></main>
}
