import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { CheckCircle, LogOut, RefreshCw, XCircle } from "lucide-react";
import { getFirebaseAuth } from "@/lib/firebase";
import { onAuthStateChanged, signOut } from "firebase/auth";
import { approveManualPayment, getAdminPaymentRequests, rejectManualPayment } from "@/lib/kozena.functions";

export const Route = createFileRoute("/admin")({ component: AdminPage });

type Request = { id:string; user_id:string; phone:string; payment_phone:string; amount:number; currency:string; status:string; created_at:string; profiles?: {full_name?:string; username?:string}|null };

function AdminPage() {
  const navigate=useNavigate(); const [rows,setRows]=useState<Request[]>([]); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState<string|null>(null); const [error,setError]=useState<string|null>(null);
  async function load(){ setLoading(true); setError(null); try { const auth=getFirebaseAuth(); if(!auth) throw new Error("Firebase haijawekwa."); if(!auth.currentUser){navigate({to:"/login"});return;} const r=await getAdminPaymentRequests(); setRows(r.requests as Request[]); } catch(e){setError(e instanceof Error?e.message:"Imeshindikana kupakia.");} finally{setLoading(false);} }
  useEffect(()=>{ const auth=getFirebaseAuth(); if(!auth) return; return onAuthStateChanged(auth,(user)=>{ if(!user) navigate({to:"/login"}); else load(); }); },[]);
  async function action(id:string, approve:boolean){ setBusy(id); setError(null); try { if(approve) await approveManualPayment({data:{paymentId:id}}); else await rejectManualPayment({data:{paymentId:id}}); await load(); } catch(e){setError(e instanceof Error?e.message:"Imeshindikana.");} finally{setBusy(null);} }
  async function logout(){ const auth=getFirebaseAuth(); if(auth) await signOut(auth); navigate({to:"/login"}); }
  return <main className="min-h-screen bg-k-slate-50 p-4 md:p-8"><div className="mx-auto max-w-6xl"><div className="mb-6 flex items-center justify-between"><div><h1 className="text-2xl font-extrabold text-k-slate-900">NARAVIBE Admin</h1><p className="text-sm text-k-slate-500">Thibitisha malipo ya manual bila kufungua database.</p></div><div className="flex gap-2"><button onClick={load} className="rounded-xl border bg-white px-4 py-2 text-sm font-bold"><RefreshCw className="mr-2 inline h-4 w-4"/>Refresh</button><button onClick={logout} className="rounded-xl bg-k-dark px-4 py-2 text-sm font-bold text-white"><LogOut className="mr-2 inline h-4 w-4"/>Logout</button></div></div>{error&&<div className="mb-4 rounded-xl border border-k-red-300 bg-k-red-50 p-4 text-sm text-k-red-900">{error}</div>}<div className="overflow-x-auto rounded-2xl border bg-white"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-k-slate-50"><tr>{["USER","REGISTERED PHONE","PAYMENT PHONE","AMOUNT","STATUS","ACTION"].map(x=><th key={x} className="px-4 py-3 font-bold">{x}</th>)}</tr></thead><tbody>{loading?<tr><td colSpan={6} className="p-8 text-center">Inapakia...</td></tr>:rows.length===0?<tr><td colSpan={6} className="p-8 text-center text-k-slate-500">Hakuna malipo yanayosubiri.</td></tr>:rows.map(r=><tr key={r.id} className="border-t"><td className="px-4 py-4"><b>{r.profiles?.full_name||"—"}</b><div className="text-xs text-k-slate-500">@{r.profiles?.username||"—"}</div></td><td className="px-4 py-4">{r.phone}</td><td className="px-4 py-4 font-bold">{r.payment_phone}</td><td className="px-4 py-4">{Number(r.amount).toLocaleString()} {r.currency}</td><td className="px-4 py-4">{r.status}</td><td className="px-4 py-4"><div className="flex gap-2"><button disabled={!!busy} onClick={()=>action(r.id,true)} className="rounded-xl bg-k-green-800 px-3 py-2 font-bold text-white disabled:opacity-50"><CheckCircle className="mr-1 inline h-4 w-4"/>THIBITISHA</button><button disabled={!!busy} onClick={()=>action(r.id,false)} className="rounded-xl bg-k-red-600 px-3 py-2 font-bold text-white disabled:opacity-50"><XCircle className="mr-1 inline h-4 w-4"/>KATAA</button></div></td></tr>)}</tbody></table></div></div></main>;
}
