import {createFileRoute,useNavigate} from "@tanstack/react-router";
import {useEffect,useState,useRef} from "react"; import {useServerFn} from "@tanstack/react-start"; import {ChevronLeft,Send,X} from "lucide-react"; import {getChatSession,getChatMessages,sendChatMessage,completeChat} from "@/lib/app.functions"; import {people} from "@/data/people";
export const Route=createFileRoute("/chat/$slug")({component:Chat});
function Chat(){const {slug}=Route.useParams();const nav=useNavigate();const person=people.find(p=>p.name.toLowerCase()===slug.toLowerCase());const create=useServerFn(getChatSession),load=useServerFn(getChatMessages),send=useServerFn(sendChatMessage),complete=useServerFn(completeChat);const [sid,setSid]=useState(""),[msgs,setMsgs]=useState<any[]>([]),[draft,setDraft]=useState(""),[busy,setBusy]=useState(false),[done,setDone]=useState(false);const end=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(!person)return;void (async()=>{try{const s=await create({data:{slug:person.name.toLowerCase(),payout:Number(person.price.replace(/\D/g,""))}});setSid(String(s.id));const m=await load({data:{sessionId:String(s.id)}});setMsgs(m);if(!m.length)setMsgs([{id:"welcome",sender_type:"foreigner",content:`Hi! KARIBU 😊 What does KARIBU mean? I am ${person.name}. I want to learn more Swahili + a little English.`}]);}catch{await nav({to:"/payment"})}})()},[]);
 useEffect(()=>{end.current?.scrollIntoView({behavior:"smooth"})},[msgs]);
 if(!person)return <main className="min-h-screen grid place-items-center">Mgeni huyu hapatikani</main>;
 const sendMsg=async()=>{if(!draft.trim()||busy||done)return;setBusy(true);const text=draft.trim();setDraft("");const replies=[`Oh nice! I understand a little. What does "${text}" mean in Swahili?`, `That is interesting 😊 Can you teach me another Swahili phrase?`, `I like that! KARIBU means welcome, right? Tell me more.`, `Great! I am learning fast. Let's continue with English and Kiswahili.`];try{const r=await send({data:{sessionId:sid,content:text,foreignerReply:replies[Math.floor(Math.random()*replies.length)]}});const m=await load({data:{sessionId:sid}});setMsgs(m);if(r.completed){await complete({data:{sessionId:sid,payout:Number(person.price.replace(/\D/g,"")),personName:person.name}});setDone(true)}}catch{}finally{setBusy(false)}};
 return <main className="flex min-h-screen flex-col bg-background"><header className="flex items-center gap-3 border-b bg-card px-4 py-3"><button onClick={()=>void nav({to:"/dashboard"})} className="flex h-10 w-10 items-center justify-center rounded-xl bg-secondary"><ChevronLeft/></button><img src={person.photo} className="h-11 w-11 rounded-full object-cover"/><div><h1 className="font-black">{person.name}</h1><p className="text-xs text-success">Online · {person.topic}</p></div></header><section className="flex-1 px-4 py-5"><div className="mx-auto max-w-2xl space-y-3">{msgs.map((m:any,i:number)=><div key={m.id??i} className={m.sender_type==="user"?"flex justify-end":"flex justify-start"}><div className={m.sender_type==="user"?`max-w-[82%] rounded-2xl ${"brand-gradient"} px-4 py-3 text-sm text-primary-foreground`:"max-w-[82%] rounded-2xl bg-card px-4 py-3 text-sm shadow-card"}>{m.content}</div></div>)}<div ref={end}/></div></section><div className="sticky bottom-0 border-t bg-card p-3"><div className="mx-auto flex max-w-2xl gap-2"><input disabled={done} value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>e.key==="Enter"&&void sendMsg()} placeholder="Andika ujumbe..." className="flex-1 rounded-full border bg-background px-5 py-3"/><button disabled={busy||done} onClick={()=>void sendMsg()} className="flex h-12 w-12 items-center justify-center rounded-full bg-primary text-primary-foreground"><Send/></button></div></div>{done&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/50 p-4"><div className="w-full max-w-md rounded-3xl bg-card p-6 text-center"><div className="text-4xl">🎉</div><h2 className="mt-3 text-2xl font-black">Chat imekamilika</h2><p className="mt-2 text-sm text-muted-foreground">Malipo yako yameongezwa kwenye Current Balance.</p><button onClick={()=>void nav({to:"/dashboard"})} className="mt-5 w-full rounded-xl bg-primary py-3 font-bold text-primary-foreground">RUDI DASHBOARD</button></div></div>}</main>}
