import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useState } from "react";
import { Eye, EyeOff, ArrowLeft, UserPlus } from "lucide-react";
import { useServerFn } from "@tanstack/react-start";
import { registerUser } from "@/lib/app.functions";
import { ACTIVATION_FEE, saveRegistration } from "@/lib/session";

export const Route=createFileRoute("/register")({component:RegisterPage,head:()=>({meta:[{title:"Jisajili — NARAVIBE"},{name:"robots",content:"noindex,nofollow"}]})});
const COUNTRIES=["🇹🇿 Tanzania","🇰🇪 Kenya","🇺🇬 Uganda","🇧🇮 Burundi","🇨🇩 Congo","🇿🇲 Zambia","🇲🇼 Malawi","🌍 International"];
function RegisterPage(){
 const navigate=useNavigate();const register=useServerFn(registerUser);const [form,setForm]=useState({name:"",username:"",email:"",phone:"",country:"Tanzania",password:"",confirm:""});const [show,setShow]=useState(false);const [error,setError]=useState("");const [loading,setLoading]=useState(false);
 const set=(k:keyof typeof form,v:string)=>setForm(f=>({...f,[k]:v}));
 async function submit(e:React.FormEvent){e.preventDefault();setError("");if(form.password!==form.confirm){setError("Password hazifanani.");return}setLoading(true);try{await register({data:{name:form.name,username:form.username,email:form.email,phone:form.phone,country:form.country,password:form.password}});saveRegistration({name:form.name,username:form.username,email:form.email,phone:form.phone,country:form.country});await navigate({to:"/payment"});}catch(e){const m=e instanceof Error?e.message:"";setError(m.includes("USERNAME_EXISTS")?"Username hiyo tayari inatumika.":m.includes("EMAIL_EXISTS")?"Email hiyo tayari imesajiliwa.":m.includes("PHONE_EXISTS")?"Namba hiyo ya simu tayari imesajiliwa.":m.includes("REGISTRATION_DB_")?"Usajili umeshindikana. Tatizo la database limetokea; angalia Vercel Runtime Logs kwa [REGISTRATION].":"Usajili umeshindikana. Hakikisha taarifa zako.");}finally{setLoading(false)}}
 return <main className="min-h-screen bg-background px-4 py-8"><div className="mx-auto max-w-md"><Link to="/" className="inline-flex items-center gap-2 text-sm font-semibold text-primary"><ArrowLeft className="h-4 w-4"/> Rudi mwanzo</Link><div className="mt-4 rounded-3xl bg-card p-6 shadow-card"><img src="/favicon.png" alt="NARAVIBE" className="mx-auto h-20 w-20 rounded-2xl object-contain"/><div className="mx-auto mt-2 flex h-12 w-12 items-center justify-center rounded-full bg-primary text-primary-foreground"><UserPlus className="h-6 w-6"/></div><h1 className="mt-3 text-center text-2xl font-extrabold text-foreground">Fungua Akaunti Yako</h1><p className="mt-1 text-center text-sm text-muted-foreground">Jisajili kisha lipia TZS {ACTIVATION_FEE.toLocaleString()}.</p><form onSubmit={submit} className="mt-6 space-y-4">
 <Field label="Jina Kamili"><input required value={form.name} onChange={e=>set("name",e.target.value)} placeholder="Juma Hassan" className="w-full rounded-xl bg-secondary px-4 py-3 text-sm outline-none"/></Field>
 <Field label="Username"><input required value={form.username} onChange={e=>set("username",e.target.value.toLowerCase().replace(/[^a-z0-9_]/g,""))} placeholder="juma_2026" className="w-full rounded-xl bg-secondary px-4 py-3 text-sm outline-none"/></Field>
 <Field label="Barua Pepe"><input required type="email" value={form.email} onChange={e=>set("email",e.target.value)} placeholder="juma@gmail.com" className="w-full rounded-xl bg-secondary px-4 py-3 text-sm outline-none"/></Field>
 <Field label="Namba ya Simu"><input required type="tel" value={form.phone} onChange={e=>set("phone",e.target.value.replace(/[^0-9]/g,""))} placeholder="0712345678" className="w-full rounded-xl bg-secondary px-4 py-3 text-sm outline-none"/></Field>
 <Field label="Nchi"><select value={form.country} onChange={e=>set("country",e.target.value)} className="w-full rounded-xl bg-secondary px-4 py-3 text-sm outline-none">{COUNTRIES.map(c=><option key={c}>{c}</option>)}</select></Field>
 <Field label="Password"><div className="relative"><input required minLength={6} type={show?"text":"password"} value={form.password} onChange={e=>set("password",e.target.value)} placeholder="Angalau herufi 6" className="w-full rounded-xl bg-secondary px-4 py-3 pr-11 text-sm outline-none"/><button type="button" onClick={()=>setShow(v=>!v)} className="absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground">{show?<EyeOff className="h-4 w-4"/>:<Eye className="h-4 w-4"/>}</button></div></Field>
 <Field label="Confirm Password"><input required type="password" value={form.confirm} onChange={e=>set("confirm",e.target.value)} placeholder="Rudia password" className="w-full rounded-xl bg-secondary px-4 py-3 text-sm outline-none"/></Field>
 {error&&<p className="rounded-xl bg-destructive/10 p-3 text-sm font-semibold text-destructive">{error}</p>}
 <button disabled={loading} className="w-full rounded-full bg-primary py-3.5 font-bold text-primary-foreground disabled:opacity-60">{loading?"INASAJILI...":"JISAJILI"}</button><p className="text-center text-xs text-muted-foreground">Baada ya usajili utaelekezwa kwenye malipo.</p><p className="text-center text-xs text-muted-foreground">Tayari una account? <Link to="/login" className="font-bold text-primary">Ingia hapa</Link></p></form></div></div></main>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="mb-1 block text-sm font-semibold text-foreground">{label}</span>{children}</label>}
